spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finish_app
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://localhost:27017/finish_app
    redis:
      host: localhost
      port: 6379
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true 